[package]
name = "launcher"
version = "2.0.0"
authors = ["https://github.com/AdoptOpenJDK/icedtea-web/graphs/contributors"]
build = "build.rs"

[dependencies]
[target.'cfg(windows)'.dependencies]
dunce = "1.0.0"
